package com.godfrey.ai_immigration_document_analyzer.analytics.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * ============================================================================
 * FRAUD ANALYTICS ENTITY
 * ============================================================================
 *
 * Persists real-time AI fraud-analysis results generated by the fraud
 * analytics pipeline.
 *
 * Responsibilities:
 *
 * - Store the fraud rule that was triggered.
 * - Store the calculated fraud score.
 * - Store whether fraud was detected.
 * - Store model confidence.
 * - Store the timestamp at which the result was created.
 *
 * Database table:
 *
 *     FRAUD_ANALYTICS
 *
 * This entity is intentionally kept aligned with the existing database
 * structure and repository layer.
 *
 * ============================================================================
 */
@Data
@Entity
@Table(
        name = "FRAUD_ANALYTICS",
        indexes = {
                @Index(
                        name = "IDX_RULE_ID",
                        columnList = "RULE_ID"
                ),
                @Index(
                        name = "IDX_CREATED_AT",
                        columnList = "CREATED_AT"
                ),
                @Index(
                        name = "IDX_FRAUD_FLAG",
                        columnList = "FRAUD_FLAG"
                )
        }
)
public class FraudAnalyticsEntity {

    /**
     * =========================================================================
     * PRIMARY KEY
     * =========================================================================
     *
     * Oracle-generated identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(
            name = "ID",
            nullable = false
    )
    private Long id;


    /**
     * =========================================================================
     * FRAUD RULE
     * =========================================================================
     *
     * Identifies the fraud-detection rule that produced the result.
     */
    @Column(
            name = "RULE_ID",
            length = 50,
            nullable = false
    )
    private String ruleId;


    /**
     * =========================================================================
     * FRAUD SCORE
     * =========================================================================
     *
     * Numerical fraud score generated by the fraud scoring engine.
     */
    @Column(
            name = "FRAUD_SCORE",
            nullable = false
    )
    private double fraudScore;


    /**
     * =========================================================================
     * FRAUD FLAG
     * =========================================================================
     *
     * Indicates whether the document was classified as potentially
     * fraudulent.
     */
    @Column(
            name = "FRAUD_FLAG",
            nullable = false
    )
    private boolean fraudFlag;


    /**
     * =========================================================================
     * CONFIDENCE
     * =========================================================================
     *
     * Confidence value associated with the fraud analysis result.
     */
    @Column(
            name = "CONFIDENCE",
            nullable = false
    )
    private double confidence;


    /**
     * =========================================================================
     * CREATED TIMESTAMP
     * =========================================================================
     *
     * Timestamp at which this analytics record was created.
     *
     * updatable = false ensures that an existing fraud-analysis timestamp
     * cannot accidentally be modified during an update.
     */
    @Column(
            name = "CREATED_AT",
            nullable = false,
            updatable = false
    )
    private LocalDateTime createdAt;


    /**
     * =========================================================================
     * PRE-PERSIST
     * =========================================================================
     *
     * Automatically initializes the creation timestamp before the entity
     * is inserted into Oracle.
     */
    @PrePersist
    protected void prePersist() {

        if (this.createdAt == null) {
            this.createdAt = LocalDateTime.now();
        }
    }
}