CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(500) NOT NULL,
    role VARCHAR2(50) DEFAULT 'USER',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE documents (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    document_type VARCHAR2(100) NOT NULL,
    file_name VARCHAR2(255) NOT NULL,
    file_path VARCHAR2(1000) UNIQUE NOT NULL,
    file_size NUMBER,
    mime_type VARCHAR2(100),
    extracted_text CLOB,
    summary CLOB,
    fraud_detected NUMBER(1) DEFAULT 0,
    risk_level VARCHAR2(20) DEFAULT 'LOW',
    upload_status VARCHAR2(30) DEFAULT 'PENDING',
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_document_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_document_user_id ON documents(user_id);
CREATE INDEX idx_document_uploaded_at ON documents(uploaded_at);