-- ============================================================================
-- FACT FOUNDATION
-- ============================================================================
-- Introduces the MukondoGTech AI Fact Model foundation: atomic,
-- provenance-tagged, temporally-scoped Facts; their supporting Evidence;
-- pairwise Conflicts; a transactional audit Timeline; Case Worker/System
-- Administrator case-data authorization (CaseAssignment); and a
-- security-sensitive access audit log.
--
-- Forward-only, additive migration - no existing table is altered.
-- ============================================================================

CREATE TABLE facts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id NUMBER NOT NULL,
    category VARCHAR2(40) NOT NULL,
    fact_key VARCHAR2(150) NOT NULL,
    value_type VARCHAR2(20) NOT NULL,
    string_value VARCHAR2(2000),
    date_value TIMESTAMP,
    number_value NUMBER,
    boolean_value NUMBER(1),
    status VARCHAR2(30) NOT NULL,
    provenance_type VARCHAR2(40) NOT NULL,
    created_by_accessor_type VARCHAR2(20) NOT NULL,
    created_by_user_id NUMBER,
    source_document_id NUMBER,
    source_locator VARCHAR2(255),
    source_snippet VARCHAR2(500),
    source_description VARCHAR2(500),
    sensitivity_tier VARCHAR2(30) NOT NULL,
    confidence_score NUMBER NOT NULL,
    confidence_level VARCHAR2(20) NOT NULL,
    confidence_explanation VARCHAR2(500),
    is_verified NUMBER(1) DEFAULT 0 NOT NULL,
    verified_at TIMESTAMP,
    verified_by_user_id NUMBER,
    verification_method VARCHAR2(40),
    verification_notes VARCHAR2(500),
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    observed_at TIMESTAMP NOT NULL,
    last_observed_at TIMESTAMP NOT NULL,
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    supersedes_fact_id NUMBER,
    retraction_reason VARCHAR2(500),
    rejection_reason VARCHAR2(500),
    CONSTRAINT fk_fact_subject_user FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_fact_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_fact_verified_by FOREIGN KEY (verified_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_fact_source_document FOREIGN KEY (source_document_id) REFERENCES documents(id),
    CONSTRAINT fk_fact_supersedes FOREIGN KEY (supersedes_fact_id) REFERENCES facts(id)
);

CREATE INDEX idx_fact_subject ON facts(subject_user_id);
CREATE INDEX idx_fact_subject_key ON facts(subject_user_id, fact_key);
CREATE INDEX idx_fact_status ON facts(status);
CREATE INDEX idx_fact_category ON facts(category);
CREATE INDEX idx_fact_supersedes ON facts(supersedes_fact_id);


CREATE TABLE fact_evidence (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fact_id NUMBER NOT NULL,
    source_type VARCHAR2(30) NOT NULL,
    document_id NUMBER,
    source_locator VARCHAR2(255),
    source_snippet VARCHAR2(500),
    reliability_note VARCHAR2(255),
    captured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_evidence_fact FOREIGN KEY (fact_id) REFERENCES facts(id),
    CONSTRAINT fk_evidence_document FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE INDEX idx_fact_evidence_fact ON fact_evidence(fact_id);
CREATE INDEX idx_fact_evidence_document ON fact_evidence(document_id);


-- "Derived from" edges for AI_INFERENCE/DERIVED_FACT provenance - not yet
-- populated by any reasoning process (Assessment/inference logic is a
-- later stage); the table exists now so provenance is never retrofitted.
CREATE TABLE fact_derivations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    derived_fact_id NUMBER NOT NULL,
    source_fact_id NUMBER NOT NULL,
    CONSTRAINT fk_derivation_derived FOREIGN KEY (derived_fact_id) REFERENCES facts(id),
    CONSTRAINT fk_derivation_source FOREIGN KEY (source_fact_id) REFERENCES facts(id)
);

CREATE INDEX idx_fact_deriv_derived ON fact_derivations(derived_fact_id);
CREATE INDEX idx_fact_deriv_source ON fact_derivations(source_fact_id);


-- Modeled pairwise (fact_a/fact_b) for this stage, not as an N-way join -
-- every approved scenario was pairwise. CONFLICT DETECTED is never FRAUD
-- DETECTED: nothing in this table's lifecycle may record a fraud label.
CREATE TABLE fact_conflicts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id NUMBER NOT NULL,
    fact_key VARCHAR2(150) NOT NULL,
    fact_a_id NUMBER NOT NULL,
    fact_b_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at TIMESTAMP,
    resolution_type VARCHAR2(30),
    resolved_by_user_id NUMBER,
    winning_fact_id NUMBER,
    resolution_notes VARCHAR2(1000),
    CONSTRAINT fk_conflict_subject FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_conflict_fact_a FOREIGN KEY (fact_a_id) REFERENCES facts(id),
    CONSTRAINT fk_conflict_fact_b FOREIGN KEY (fact_b_id) REFERENCES facts(id),
    CONSTRAINT fk_conflict_winning FOREIGN KEY (winning_fact_id) REFERENCES facts(id),
    CONSTRAINT fk_conflict_resolved_by FOREIGN KEY (resolved_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_fact_conflict_subject ON fact_conflicts(subject_user_id);
CREATE INDEX idx_fact_conflict_status ON fact_conflicts(status);
CREATE INDEX idx_fact_conflict_fact_a ON fact_conflicts(fact_a_id);
CREATE INDEX idx_fact_conflict_fact_b ON fact_conflicts(fact_b_id);


-- Transactional, append-only audit history. Every writer in the Fact
-- foundation commits its event in the SAME transaction as the state
-- change it describes - never a best-effort/asynchronous log.
CREATE TABLE fact_timeline_events (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id NUMBER NOT NULL,
    event_type VARCHAR2(40) NOT NULL,
    fact_id NUMBER,
    conflict_id NUMBER,
    actor_type VARCHAR2(20) NOT NULL,
    actor_user_id NUMBER,
    previous_status VARCHAR2(30),
    new_status VARCHAR2(30),
    reason VARCHAR2(500),
    occurred_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_timeline_subject FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_timeline_fact FOREIGN KEY (fact_id) REFERENCES facts(id),
    CONSTRAINT fk_timeline_conflict FOREIGN KEY (conflict_id) REFERENCES fact_conflicts(id),
    CONSTRAINT fk_timeline_actor FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_timeline_subject ON fact_timeline_events(subject_user_id);
CREATE INDEX idx_timeline_fact ON fact_timeline_events(fact_id);
CREATE INDEX idx_timeline_occurred_at ON fact_timeline_events(occurred_at);


-- Authorizes a CASE_WORKER-role user to access a specific subject's Facts.
-- Holding the ADMIN role alone grants no row here and therefore no Fact
-- access - see FactAuthorizationService.
CREATE TABLE case_assignments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_worker_user_id NUMBER NOT NULL,
    subject_user_id NUMBER NOT NULL,
    assigned_by_user_id NUMBER,
    active NUMBER(1) DEFAULT 1 NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_assignment_worker FOREIGN KEY (case_worker_user_id) REFERENCES users(id),
    CONSTRAINT fk_assignment_subject FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_assignment_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_assignment_worker ON case_assignments(case_worker_user_id);
CREATE INDEX idx_assignment_subject ON case_assignments(subject_user_id);
CREATE INDEX idx_assignment_worker_subject ON case_assignments(case_worker_user_id, subject_user_id);


-- Records WHO read WHICH facts, WHEN, for what declared purpose - distinct
-- from fact_timeline_events, which records what is known rather than who
-- looked at it. Both granted and denied attempts are logged.
CREATE TABLE fact_access_audit_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_user_id NUMBER NOT NULL,
    fact_id NUMBER,
    accessed_by_user_id NUMBER,
    accessor_type VARCHAR2(20) NOT NULL,
    purpose VARCHAR2(255),
    sensitivity_tier_accessed VARCHAR2(30),
    granted NUMBER(1) NOT NULL,
    denial_reason VARCHAR2(255),
    accessed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_subject FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_audit_fact FOREIGN KEY (fact_id) REFERENCES facts(id),
    CONSTRAINT fk_audit_accessed_by FOREIGN KEY (accessed_by_user_id) REFERENCES users(id)
);

CREATE INDEX idx_access_audit_subject ON fact_access_audit_log(subject_user_id);
CREATE INDEX idx_access_audit_accessor ON fact_access_audit_log(accessed_by_user_id);
CREATE INDEX idx_access_audit_at ON fact_access_audit_log(accessed_at);
