-- ============================================================================
-- REQUIREMENT / PATHWAY FOUNDATION
-- ============================================================================
-- Introduces the MukondoGTech AI Requirement/Pathway layer: versioned
-- regulatory sources; canonical, impersonal Requirement definitions with a
-- closed-grammar logic representation; Requirement-to-Fact evidence
-- bindings; Pathway catalogue entries that reference (never duplicate)
-- Requirements; and the personalized, disposable RequirementEvaluation/
-- PathwayAssessment results of evaluating them against one subject's Facts.
--
-- Builds strictly on top of the existing Fact Foundation (facts,
-- fact_conflicts, users) - no existing table is altered. Forward-only,
-- additive migration.
-- ============================================================================

CREATE TABLE regulatory_versions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    regulation_identity VARCHAR2(150) NOT NULL,
    jurisdiction VARCHAR2(100) NOT NULL,
    source_type VARCHAR2(40) NOT NULL,
    source_authority VARCHAR2(255) NOT NULL,
    source_reference VARCHAR2(500),
    publication_date TIMESTAMP,
    retrieval_date TIMESTAMP,
    effective_from TIMESTAMP,
    effective_to TIMESTAMP,
    supersedes_version_id NUMBER,
    superseded_by_version_id NUMBER,
    verification_status VARCHAR2(30) NOT NULL,
    change_summary VARCHAR2(1000),
    recorded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_reg_version_supersedes FOREIGN KEY (supersedes_version_id) REFERENCES regulatory_versions(id),
    CONSTRAINT fk_reg_version_superseded_by FOREIGN KEY (superseded_by_version_id) REFERENCES regulatory_versions(id)
);

CREATE INDEX idx_reg_version_regulation ON regulatory_versions(regulation_identity);
CREATE INDEX idx_reg_version_jurisdiction ON regulatory_versions(jurisdiction);
CREATE INDEX idx_reg_version_effective ON regulatory_versions(effective_from, effective_to);


-- A RULE, never a result - see RequirementEvaluation for the personalized
-- outcome of applying one row here to one subject. One row per
-- regulatory_version_id: a rule change is a new row, never an in-place edit.
CREATE TABLE requirements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_key VARCHAR2(150) NOT NULL,
    requirement_type VARCHAR2(40) NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(2000),
    jurisdiction VARCHAR2(100) NOT NULL,
    immigration_context VARCHAR2(100),
    regulatory_version_id NUMBER NOT NULL,
    mandatory NUMBER(1) DEFAULT 1 NOT NULL,
    applicability_logic CLOB,
    satisfaction_logic CLOB NOT NULL,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_requirement_reg_version FOREIGN KEY (regulatory_version_id) REFERENCES regulatory_versions(id)
);

CREATE INDEX idx_requirement_key ON requirements(requirement_key);
CREATE INDEX idx_requirement_type ON requirements(requirement_type);
CREATE INDEX idx_requirement_status ON requirements(status);
CREATE INDEX idx_requirement_reg_version ON requirements(regulatory_version_id);


-- Declares one Fact key a Requirement may read and the minimum evidence
-- quality expected of it. A Fact failing this bar yields
-- INSUFFICIENT_EVIDENCE, never NOT_SATISFIED - see LogicEvaluationService.
CREATE TABLE requirement_fact_bindings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id NUMBER NOT NULL,
    fact_key VARCHAR2(150) NOT NULL,
    requires_verification NUMBER(1) DEFAULT 0 NOT NULL,
    minimum_provenance_type VARCHAR2(40),
    CONSTRAINT fk_req_binding_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

CREATE INDEX idx_req_binding_requirement ON requirement_fact_bindings(requirement_id);
CREATE INDEX idx_req_binding_fact_key ON requirement_fact_bindings(fact_key);


-- Knowledge about a possible immigration ROUTE, never a person's
-- application - see the pre-existing applications table for that. No
-- subject_user_id column exists here or ever should. composition_logic
-- references Requirements by id (REQUIREMENT_REF nodes) - never duplicates
-- their definitions.
CREATE TABLE pathways (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pathway_key VARCHAR2(150) NOT NULL,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(2000),
    jurisdiction VARCHAR2(100) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    composition_logic CLOB NOT NULL,
    evidence_expectations CLOB,
    valid_from TIMESTAMP,
    valid_to TIMESTAMP,
    status VARCHAR2(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_pathway_key ON pathways(pathway_key);
CREATE INDEX idx_pathway_jurisdiction ON pathways(jurisdiction);
CREATE INDEX idx_pathway_status ON pathways(status);


-- The RESULT of applying one Requirement (at one regulatory version) to one
-- subject's Facts as of one assessment date. Personal, disposable, always
-- re-derivable - never itself a Fact, never mutated once recorded.
CREATE TABLE requirement_evaluations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id NUMBER NOT NULL,
    regulatory_version_id NUMBER NOT NULL,
    subject_user_id NUMBER NOT NULL,
    assessment_date TIMESTAMP NOT NULL,
    outcome VARCHAR2(30) NOT NULL,
    certainty_score NUMBER(5,4),
    certainty_level VARCHAR2(20) NOT NULL,
    explanation VARCHAR2(1000),
    derived_values_json CLOB,
    evaluated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_req_eval_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id),
    CONSTRAINT fk_req_eval_reg_version FOREIGN KEY (regulatory_version_id) REFERENCES regulatory_versions(id),
    CONSTRAINT fk_req_eval_subject FOREIGN KEY (subject_user_id) REFERENCES users(id)
);

CREATE INDEX idx_req_eval_requirement ON requirement_evaluations(requirement_id);
CREATE INDEX idx_req_eval_subject ON requirement_evaluations(subject_user_id);
CREATE INDEX idx_req_eval_subject_req ON requirement_evaluations(subject_user_id, requirement_id);
CREATE INDEX idx_req_eval_outcome ON requirement_evaluations(outcome);


-- Evidence trail: which Facts were actually read to produce one evaluation.
-- A reference only - never a copy of the Fact's value.
CREATE TABLE requirement_evaluation_facts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id NUMBER NOT NULL,
    fact_id NUMBER NOT NULL,
    CONSTRAINT fk_req_eval_fact_eval FOREIGN KEY (evaluation_id) REFERENCES requirement_evaluations(id),
    CONSTRAINT fk_req_eval_fact_fact FOREIGN KEY (fact_id) REFERENCES facts(id)
);

CREATE INDEX idx_req_eval_fact_eval ON requirement_evaluation_facts(evaluation_id);
CREATE INDEX idx_req_eval_fact_fact ON requirement_evaluation_facts(fact_id);


-- Which open Fact conflicts blocked an evaluation from reaching a
-- definitive answer (CONFLICTED outcome). References the existing Fact
-- Foundation conflict record - never a fraud determination.
CREATE TABLE requirement_evaluation_conflicts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id NUMBER NOT NULL,
    conflict_id NUMBER NOT NULL,
    CONSTRAINT fk_req_eval_conflict_eval FOREIGN KEY (evaluation_id) REFERENCES requirement_evaluations(id),
    CONSTRAINT fk_req_eval_conflict_conflict FOREIGN KEY (conflict_id) REFERENCES fact_conflicts(id)
);

CREATE INDEX idx_req_eval_conflict_eval ON requirement_evaluation_conflicts(evaluation_id);
CREATE INDEX idx_req_eval_conflict_conflict ON requirement_evaluation_conflicts(conflict_id);


-- The personalized, terminal artifact of evaluating one Pathway against one
-- subject's Facts. References pathways by id only - the Pathway itself is
-- never mutated or copied into.
CREATE TABLE pathway_assessments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pathway_id NUMBER NOT NULL,
    subject_user_id NUMBER NOT NULL,
    assessment_date TIMESTAMP NOT NULL,
    outcome VARCHAR2(30) NOT NULL,
    assessment_confidence_score NUMBER(5,4),
    assessment_confidence_level VARCHAR2(20) NOT NULL,
    computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_pathway_assessment_pathway FOREIGN KEY (pathway_id) REFERENCES pathways(id),
    CONSTRAINT fk_pathway_assessment_subject FOREIGN KEY (subject_user_id) REFERENCES users(id)
);

CREATE INDEX idx_pathway_assessment_pathway ON pathway_assessments(pathway_id);
CREATE INDEX idx_pathway_assessment_subject ON pathway_assessments(subject_user_id);
CREATE INDEX idx_pathway_assessment_subj_pathway ON pathway_assessments(subject_user_id, pathway_id);


-- Middle link in the explainability chain PATHWAY -> REQUIREMENT ->
-- REQUIREMENT EVALUATION: every RequirementEvaluation that fed one
-- PathwayAssessment.
CREATE TABLE pathway_assessment_req_evals (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assessment_id NUMBER NOT NULL,
    evaluation_id NUMBER NOT NULL,
    CONSTRAINT fk_pa_req_eval_assessment FOREIGN KEY (assessment_id) REFERENCES pathway_assessments(id),
    CONSTRAINT fk_pa_req_eval_evaluation FOREIGN KEY (evaluation_id) REFERENCES requirement_evaluations(id)
);

CREATE INDEX idx_pa_req_eval_assessment ON pathway_assessment_req_evals(assessment_id);
CREATE INDEX idx_pa_req_eval_evaluation ON pathway_assessment_req_evals(evaluation_id);
