-- ============================================================================
-- EVIDENCE INTELLIGENCE GRAPH FOUNDATION
-- ============================================================================
-- Introduces the two additive entities identified as genuine gaps by the
-- Evidence Intelligence Graph architecture review: DOCUMENT_VERSIONS
-- (Document has no version axis today) and EVIDENCE_ITEMS (FACT_EVIDENCE is
-- too thin to carry a lifecycle, a multi-dimensional strength vector, or
-- support for more than one Fact).
--
-- Builds strictly on top of the existing Fact Foundation and Document
-- pipeline - no existing table's columns are altered or removed, and no
-- existing row's meaning changes. FACT_EVIDENCE gains one nullable,
-- backward-compatible foreign key so already-committed rows keep working
-- unmodified; new writes may optionally populate it.
--
-- Everything else the Evidence Intelligence Graph traverses (Fact,
-- FactConflict, Requirement, RequirementEvaluation, Pathway,
-- PathwayAssessment, RegulatoryVersion) is reused exactly as it exists
-- today - no parallel entity is introduced for any of them.
--
-- Forward-only, additive migration.
-- ============================================================================

-- One immutable, point-in-time state of a Document's content/extraction.
-- Re-upload or re-OCR of the same logical document currently overwrites
-- Document.extractedText in place; this table is what makes "which reading
-- of this document produced this evidence" answerable, and lets a
-- document's own issue/expiry dates be tracked independently of any Fact
-- it happens to support.
CREATE TABLE document_versions (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id NUMBER NOT NULL,
    version_number NUMBER NOT NULL,
    extraction_method VARCHAR2(60),
    extracted_text_ref VARCHAR2(500),
    document_issue_date TIMESTAMP,
    document_expiry_date TIMESTAMP,
    superseded_by_version_id NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_doc_version_document FOREIGN KEY (document_id) REFERENCES documents(id),
    CONSTRAINT fk_doc_version_superseded_by FOREIGN KEY (superseded_by_version_id) REFERENCES document_versions(id)
);

CREATE INDEX idx_doc_version_document ON document_versions(document_id, version_number);


-- One piece of evidentiary material as a first-class, lifecycle-bearing
-- object - independent of whether it has (yet) produced an accepted Fact.
-- FACT_EVIDENCE remains the Document<->Fact linkage row; an EVIDENCE_ITEMS
-- row is an optional enrichment of it, never a replacement.
--
-- CRITICAL, non-negotiable invariant carried over from the Fact Foundation:
-- nothing in this table may ever set or imply Fact verification
-- (facts.is_verified) - that overlay is set exclusively by
-- FactLifecycleService.verify(). This table also never stores a "fraud"
-- determination of any kind - Document.fraud_detected/risk_level remain
-- the only, explicitly non-forensic, legacy signal of that kind, and feed
-- this table only indirectly, as one input a caller may consider when
-- setting extraction_confidence - never copied or aliased here.
CREATE TABLE evidence_items (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_version_id NUMBER,
    source_type VARCHAR2(30) NOT NULL,
    status VARCHAR2(30) NOT NULL,
    directness VARCHAR2(20),
    extraction_confidence NUMBER(5,4),
    source_snippet VARCHAR2(500),
    extracted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    rejection_reason VARCHAR2(500),
    CONSTRAINT fk_evidence_item_doc_version FOREIGN KEY (document_version_id) REFERENCES document_versions(id)
);

CREATE INDEX idx_evidence_item_doc_version ON evidence_items(document_version_id);
CREATE INDEX idx_evidence_item_status ON evidence_items(status);


-- Additive, backward-compatible link from the existing evidence attestation
-- row to its optional richer EvidenceItem. Nullable: every FACT_EVIDENCE
-- row committed before this migration keeps working exactly as before.
ALTER TABLE fact_evidence ADD evidence_item_id NUMBER;

ALTER TABLE fact_evidence
    ADD CONSTRAINT fk_fact_evidence_item FOREIGN KEY (evidence_item_id) REFERENCES evidence_items(id);

CREATE INDEX idx_fact_evidence_item ON fact_evidence(evidence_item_id);


-- Closes an indexing gap identified during the Evidence Intelligence Graph
-- design review: FACT_CONFLICTS had no index on fact_key, needed for the
-- "conflict cluster" query (every open/resolved conflict touching one
-- factKey, presented as one grouped view without any new storage).
CREATE INDEX idx_fact_conflict_fact_key ON fact_conflicts(fact_key);
