-- ============================================================================
-- AGENT RUN FOUNDATION (Phase 5.1 - EXPLAIN_REQUIREMENT)
-- ============================================================================
-- Introduces the one new persistence unit Phase 5.1 genuinely requires: an
-- auditable record of one agent invocation (goal, plan, tools invoked,
-- grounding state, structured result, human-review state).
--
-- A final inspection of the existing audit/history infrastructure (
-- FACT_ACCESS_AUDIT_LOG, AiAuditService, AIModelMonitoringService, CHAT_LOGS)
-- found none of them shaped to represent this: FACT_ACCESS_AUDIT_LOG records
-- a single Fact-view decision (no goal, no plan, no tool list, no result);
-- AiAuditService backs an admin document/application scan action, not an
-- agent run; AIModelMonitoringService is explicitly in-memory only and reset
-- on restart; CHAT_LOGS records only session/length/latency metrics, no
-- question/answer/result. None can represent an AgentRun without distorting
-- its own meaning, so a new, additive table is genuinely necessary.
--
-- Forward-only, additive migration - no existing table is altered.
-- ============================================================================

CREATE TABLE agent_runs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Fixed to 'EXPLAIN_REQUIREMENT' in Phase 5.1 - see AgentGoalType.
    goal VARCHAR2(50) NOT NULL,

    -- The case this run is about (never trusted from the caller directly -
    -- always re-derived from the PathwayAssessment, exactly like every
    -- other case-scoped service in this codebase).
    subject_user_id NUMBER NOT NULL,

    -- Who actually asked (the authenticated caller - self, or an assigned
    -- case worker; never elevated by any AI-specific privilege).
    requested_by_user_id NUMBER NOT NULL,

    pathway_assessment_id NUMBER,
    requirement_id NUMBER,

    -- COMPLETED / INSUFFICIENT_EVIDENCE / FAILED - see AgentRunStatus.
    status VARCHAR2(30) NOT NULL,

    -- The fixed, human-readable plan this run executed (never hidden
    -- chain-of-thought - a short, auditable step list).
    plan_summary VARCHAR2(2000),

    -- Comma-separated AgentToolName values actually invoked, in order.
    tools_invoked VARCHAR2(500),

    -- The real model that produced the explanation, as reported by the
    -- provider's own response metadata (same pattern as
    -- AIModelMonitoringService.resolveModelName) - null when the LLM was
    -- never invoked (e.g. insufficient evidence, or a tool failure).
    model VARCHAR2(100),

    -- Concise, auditable reasoning summary - never raw chain-of-thought.
    reasoning_summary VARCHAR2(2000),

    -- The full structured ExplainRequirementResult, serialized, so a
    -- completed run can be re-fetched (GET /api/agent/runs/{id}) without
    -- re-executing the agent.
    result_json CLOB,

    -- GROUNDED / INSUFFICIENT_EVIDENCE - whether the gathered case data was
    -- sufficient to ground an explanation at all.
    grounding_state VARCHAR2(30),

    human_review_required NUMBER(1) DEFAULT 0 NOT NULL,

    error_message VARCHAR2(1000),

    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,

    CONSTRAINT fk_agent_run_subject FOREIGN KEY (subject_user_id) REFERENCES users(id),
    CONSTRAINT fk_agent_run_requested_by FOREIGN KEY (requested_by_user_id) REFERENCES users(id),
    CONSTRAINT fk_agent_run_pathway_assessment FOREIGN KEY (pathway_assessment_id) REFERENCES pathway_assessments(id),
    CONSTRAINT fk_agent_run_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id)
);

CREATE INDEX idx_agent_run_subject ON agent_runs(subject_user_id);
CREATE INDEX idx_agent_run_requirement ON agent_runs(requirement_id);
CREATE INDEX idx_agent_run_status ON agent_runs(status);
