CREATE TABLE fraud_analytics (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id VARCHAR2(50) NOT NULL,
    fraud_score NUMBER(10,4) NOT NULL,
    fraud_flag NUMBER(1) NOT NULL,
    confidence NUMBER(10,4) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_fraud_rule_id ON fraud_analytics(rule_id);
CREATE INDEX idx_fraud_created_at ON fraud_analytics(created_at);
CREATE INDEX idx_fraud_flag ON fraud_analytics(fraud_flag);