CREATE TABLE visa_rules (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR2(100) NOT NULL,
    visa_type VARCHAR2(100) NOT NULL,
    requirements CLOB NOT NULL,
    processing_time VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_country_visa_type
ON visa_rules(country, visa_type);