CREATE TABLE applications (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    full_name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL,
    phone VARCHAR2(50),
    date_of_birth DATE,
    country VARCHAR2(150) NOT NULL,
    visa_type VARCHAR2(150) NOT NULL,
    notes VARCHAR2(2000),
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    risk_level VARCHAR2(20) DEFAULT 'LOW' NOT NULL,
    ai_confidence NUMBER(5,2),
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT fk_application_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX idx_application_user ON applications(user_id);
CREATE INDEX idx_application_status ON applications(status);
CREATE INDEX idx_application_submitted_at ON applications(submitted_at);

-- Links an uploaded document to the application it was submitted for.
-- Nullable: documents can still exist independently of any application.
ALTER TABLE documents ADD application_id NUMBER;

ALTER TABLE documents ADD CONSTRAINT fk_document_application
    FOREIGN KEY (application_id) REFERENCES applications(id);

CREATE INDEX idx_document_application ON documents(application_id);
