-- Records one row per AI chat exchange, so the admin analytics page can
-- report real query volume and response-time metrics instead of
-- fabricated numbers. ConversationService keeps the actual message text
-- in memory only (per-session, capped, never persisted) - this table
-- intentionally stores no message content, only usage metrics.
CREATE TABLE chat_logs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(100) NOT NULL,
    question_length NUMBER NOT NULL,
    response_time_ms NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_chat_log_created_at ON chat_logs(created_at);
